### ISSUE TITLE
Bug in visual selection

### ISSUE THREAD

**Issue by Fabian-programmer** [nvim-telescope/telescope-live-grep-args.nvim#74] opened 2023-11-29 21:21 UTC
### Description

Hey, thanks for the plugin.

I just encountered the problem, I was visual selecting a text from right to left.
![grafik](https://github.com/nvim-telescope/telescope-live-grep-args.nvim/assets/65787013/5caef9ff-ca3a-4554-bc15-28c4be4cbe46)

I think here lies the problem:
```
  local _, ls, cs = unpack(vim.fn.getpos("v"))
  local _, le, ce = unpack(vim.fn.getpos("."))
```

when you select text from right to left, then `cs` is bigger than `ce`.

so there needs to be a condition:
```
if cs > ce
  swap(cs,ce)
  swap(ls,le)
```

https://github.com/nvim-telescope/telescope-live-grep-args.nvim/blob/master/lua/telescope-live-grep-args/shortcuts.lua#L8

### Neovim version

```markdown
nvim 0.9.4
```

### Operating system and version

ubuntu 22

### Telescope version / branch / rev

latest

### Telescope live grep args version / branch / rev

latest

### checkhealth telescope

```markdown
.
```

### Steps to reproduce

.

### Actual behavior

.

### Minimal config

```Lua
.
```

**Comment by weeman1337** [comment] 2023-12-15 14:19
Thank you for reporting the issue @Fabian-programmer 

This bug was already reported before https://github.com/nvim-telescope/telescope-live-grep-args.nvim/issues/63 Also a [pull request](https://github.com/nvim-telescope/telescope-live-grep-args.nvim/pull/69) exists, which should be merged soon.

**Comment by weeman1337** [comment] 2023-12-15 14:19
Duplicate of https://github.com/nvim-telescope/telescope-live-grep-args.nvim/issues/63

**Closed by weeman1337** 2023-12-15 14:19 UTC
Labels: bug
